name: Kuala_Penyu
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.0.0
  cupertino_icons: ^1.0.8
  pdfx: ^2.6.0
  internet_file: ^1.2.0
  universal_platform: ^1.1.0
  performance: ^0.1.1
  flutter_native_splash: ^2.3.1
  rename_app: ^1.3.2
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  assets:
    - assets/demo.pdf

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/demo.pdf

flutter_native_splash:
  color: "#ffffff"
  image: assets/image.png
  android_12:
    image: assets/image.png
